apiVersion: apps/v1
kind: Deployment
metadata:
  name: pendataan-penduduk
  namespace: default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: pendataan-penduduk
  template:
    metadata:
      labels:
        app: pendataan-penduduk
    spec:
      containers:
      - image: vourteen14/pendataan-penduduk:latest
        imagePullPolicy: Always
        name: pendataan-penduduk
        ports:
        - containerPort: 6969
        readinessProbe:
          httpGet:
             path: /
             port: 6969
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: pendataan-penduduk-service
spec:
  selector:
    app: pendataan-penduduk
  ports:
    - port: 6969
